# Generated by Django 4.1.2 on 2024-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_info_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('words', models.TextField(verbose_name='words')),
            ],
        ),
    ]
