# Generated by Django 4.1.2 on 2024-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
