# Generated by Django 4.1.2 on 2024-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='info',
            field=models.ManyToManyField(to='miniapp.info'),
        ),
    ]
