# Generated by Django 4.1.2 on 2024-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0006_route_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('site', models.URLField(max_length=500)),
            ],
        ),
    ]
